### ISSUE TITLE
Feedback on week 9 project progress

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-1/main#40]
Subject: feedback on week 9 project progress

See [v1.2 progress guide](https://nuscs2113-ay1819s2.github.io/website/admin/project-w09-v12.html) for more details of the activities mentioned below.

### Recommended progress for v1.2

-  [x]  Issue labels<sup>*</sup> set up e.g., `type.*` and `priority.*` (:heavy_check_mark: well done!)
-  [x]  All milestones `v1.2`, `v1.3`, `v1.4`, created (:heavy_check_mark: well done!)
-  [x]  Issues marked as `type.Story` e.g., [link](https://github.com/cs2113-ay1819s2-t08-1/main/issues/21) (:heavy_check_mark: well done!)
-  [x]  Some issues prioritized using `priority.*` labels e.g., [link](https://github.com/cs2113-ay1819s2-t08-1/main/issues/4) (:heavy_check_mark: well done!)
*  Milestone v1.2 _managed_ systematically
     -  [x]  A suitable deadline<sup>**</sup> set (:heavy_check_mark: well done!)
     -  [x]  Issues allocated to v1.2 e.g., [link](https://github.com/cs2113-ay1819s2-t08-1/main/issues/22) (:heavy_check_mark: well done!) 
     -  [ ]  All issues/PRs in it are closed/merged  (:exclamation: try to do by next milestone) 
     -  [ ]  Milestone closed (:exclamation: try to do by next milestone) 
     -  [ ]  Code tagged as `v1.2` (:exclamation: try to do by next milestone) 
-  [ ]  Build passing [link](https://travis-ci.org/cs2113-ay1819s2-t08-1/main/builds/104788561) (:exclamation: try to do by next milestone)
-  [ ]  Some issues assigned to milestone v1.3 e.g.,  (:exclamation: try to do by next milestone)

 <sup>*</sup>Remember to use the format specified, else it will not be picked up by the bot
<sup>**</sup>Remember that the deadline is the midnight before your tutorials

Not graded:
- [x] Updated User Guide for v1.2  (:+1:  Kudos!)

### Follow up from v1.1

* Used forking workflow:
     -  [x]  Created PRs [link](https://github.com/cs2113-ay1819s2-t08-1/main/pull/16) (:heavy_check_mark: well done!)
     -  [ ]  Gave review comments to other PRs (:exclamation: try to do by next milestone)

- [x]  Merged updates to documents (:heavy_check_mark: well done!)
- [x]  `swalahlah.png` uploaded and linked from AboutUs page in png format (change image to png if presently in different format) (:heavy_check_mark: well done!)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [ ]  Merged updates to the Developer Guide (:exclamation: try to do by next milestone)
  - [x]  Has issues/PRs assigned for the milestone (:heavy_check_mark: well done!)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Merged updates to the Developer Guide (:heavy_check_mark: well done!)
  - [x]  Has issues/PRs assigned for the milestone (:heavy_check_mark: well done!)

### Follow up from v1.1

* Used forking workflow:
     -  [x]  Created PRs [link](https://github.com/cs2113-ay1819s2-t08-1/main/pull/8) (:heavy_check_mark: well done!)
     -  [ ]  Gave review comments to other PRs (:exclamation: try to do by next milestone)

- [x]  Merged updates to documents (:heavy_check_mark: well done!)
- [x]  `articstranger.png` uploaded and linked from AboutUs page in png format (change image to png if presently in different format) (:heavy_check_mark: well done!)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Merged updates to the Developer Guide (:heavy_check_mark: well done!)
  - [x]  Has issues/PRs assigned for the milestone (:heavy_check_mark: well done!)

### Follow up from v1.1

* Used forking workflow:
     -  [x]  Created PRs [link](https://github.com/cs2113-ay1819s2-t08-1/main/pull/5) (:heavy_check_mark: well done!)
     -  [ ]  Gave review comments to other PRs (:exclamation: try to do by next milestone)

- [x]  Merged updates to documents (:heavy_check_mark: well done!)
- [x]  `quinnzzzzz.png` uploaded and linked from AboutUs page in png format (change image to png if presently in different format) (:heavy_check_mark: well done!)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [ ]  Merged updates to the Developer Guide (:exclamation: try to do by next milestone)
  - [x]  Has issues/PRs assigned for the milestone (:heavy_check_mark: well done!)

Tutor: @RubaP

Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-03-19 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.
